/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImageViewer.java
 *
 * Created on Feb 14, 2013, 1:38:47 PM
 */
package com.gsom.images.ui.resources;

import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/**
 *
 * @author Ruchira
 */
public class ImageViewer extends javax.swing.JFrame {

    JPanel forImage = new JPanel();

    /** Creates new form ImageViewer */
    public ImageViewer() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jButton1.setText("Save");
        Image imge = null;
        File file = null;
        jScrollPane1.setViewportView(jPanel2);


        // values.map should be already initialized when user clicks the 'Show'
        // button in the main window
        HashMap<String, String> map = Values.map;


        if (map.containsKey(Values.REQUIRED_GSOM_NODE)) {
            String[] images = map.get(Values.REQUIRED_GSOM_NODE).split(",");
            forImage.setLayout(new GridLayout((int) images.length / 7, 7, 4, 4));
            for (String img : images) {
                file = new File(Values.IMAGE_FOLDER_LOCATION + "\\" + img + ".jpg");
                try {
                    System.out.println("> file: " + file);
                    imge = ImageIO.read(file).getScaledInstance(100, 100, BufferedImage.SCALE_SMOOTH);
                } catch (IOException ex) {
                    Logger.getLogger(ImageViewer.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (StartApp.getThubnailImage(imge, file) != null) {
                    forImage.add(StartApp.getThubnailImage(imge, file));
                }

            }
        }

        
        jPanel2.add(forImage);
        setSize(876, 524);
        setTitle("Feature Extraction Viewer");
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(ImageViewer.class);
        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(resourceMap.getColor("jScrollPane1.background")); // NOI18N
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jPanel2.setMaximumSize(null);
        jPanel2.setName("jPanel2"); // NOI18N
        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 830, 410));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 860, 450);

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 450, 95, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        BufferedImage bi = new BufferedImage(forImage.getWidth(), forImage.getHeight(), BufferedImage.TYPE_INT_RGB);
        Graphics g = bi.createGraphics();
        forImage.print(g);
        g.dispose();
        try {
            ImageIO.write(bi, "jpg", new File("ImagesSet.jpg"));
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) throws IOException {
//        // Image img = ImageIO.read(new File("D:\\MyProjects\\FYP\\MPEG_7\\li_photograph\\image.cd\\2\\20090.jpg")).getScaledInstance(100, 100, BufferedImage.SCALE_SMOOTH);
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new ImageViewer().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
