/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gsom.ui;

import com.gsom.core.GSOMRun;
import com.gsom.enums.InitType;
import com.gsom.enums.InputDataType;
import com.gsom.listeners.GSOMRunListener;
import com.gsom.nodes.EucDistOccMat;
import com.gsom.objects.GCluster;
import com.gsom.objects.GNode;
import com.gsom.ui.image_ui.ImageNetworkController;
import com.gsom.ui.image_ui.SingleNodeImageController;
import com.gsom.ui.image_ui.listeners.ImageNetworkControllerListener;
import com.gsom.util.GFileHandler;
import com.gsom.util.GSOMConstants;
import com.gsom.util.Utils;
import com.sun.image.codec.jpeg.JPEGCodec;
import com.sun.image.codec.jpeg.JPEGEncodeParam;
import com.sun.image.codec.jpeg.JPEGImageEncoder;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Map;
import java.util.logging.FileHandler;
import javax.swing.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.XYToolTipGenerator;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.jfree.util.ShapeUtilities;

/**
 *
 * @author Thush
 */
public class MainWindow extends javax.swing.JFrame implements GSOMRunListener, ImageNetworkControllerListener {

    public static int distance;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setLocationRelativeTo(null);
        for (InputDataType i : InputDataType.values()) {
            fileTypeCombo.addItem(i.toString());
        }
        fileTypeCombo.setSelectedItem(0);
    }

    private ArrayList<Color> getColorArray(int count) {
        ArrayList<Color> plotColors = new ArrayList<Color>();

        plotColors.add(new Color(0, 0, 0));

        int[] rgb = new int[3];
        for (int j = 0; j < 3; j++) {
            rgb[j] = 0;
        }
        //int incrementVal = 40;
        for (int i = 0; i < 3; i++) {

            rgb[i] = 255;
            plotColors.add(new Color(rgb[0], rgb[1], rgb[2]));
            if (plotColors.size() == count) {
                return plotColors;
            }
            rgb[i] = 0;
        }

        for (int j = 0; j < 3; j++) {
            rgb[j] = 0;
        }

        for (int i = 0; i < 3; i++) {

            rgb[i] = 255;

            for (int j = 0; j < 3; j++) {
                rgb[j] = 255;
                if (i != j) {
                    plotColors.add(new Color(rgb[0], rgb[1], rgb[2]));
                }
                rgb[j] = 0;
                if (plotColors.size() == count) {
                    return plotColors;
                }
            }
            rgb[i] = 0;
        }


        return plotColors;
    }

    public static void saveToFile(JFreeChart chart,
            String aFileName,
            int width,
            int height,
            double quality)
            throws FileNotFoundException, IOException {
        BufferedImage img = draw(chart, width, height);

        FileOutputStream fos = new FileOutputStream(aFileName);
        JPEGImageEncoder encoder2 =
                JPEGCodec.createJPEGEncoder(fos);
        JPEGEncodeParam param2 =
                encoder2.getDefaultJPEGEncodeParam(img);
        param2.setQuality((float) quality, true);
        encoder2.encode(img, param2);
        fos.close();
    }

    protected static BufferedImage draw(JFreeChart chart, int width, int height) {
        BufferedImage img =
                new BufferedImage(width, height,
                BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = img.createGraphics();

        chart.draw(g2, new Rectangle2D.Double(0, 0, width, height));

        g2.dispose();
        return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trainButton = new javax.swing.JButton();
        plotMapBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusTextArea = new javax.swing.JTextArea();
        InputFileLocationTextBox = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        initTypeCombo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jDistance = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        fileTypeCombo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        saveData = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cCountTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        maxCountLbl = new javax.swing.JLabel();
        coeffTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        calcCoeffBtn = new javax.swing.JButton();
        viewMatrixBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GSOM Train & Test Tool");
        setResizable(false);

        trainButton.setText("Train GSOM");
        trainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainButtonActionPerformed(evt);
            }
        });

        plotMapBtn.setText("Plot Results");
        plotMapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotMapBtnActionPerformed(evt);
            }
        });

        statusTextArea.setColumns(20);
        statusTextArea.setRows(5);
        jScrollPane1.setViewportView(statusTextArea);

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Input File Location");

        jButton1.setText("View Images");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic Parameters"));

        jLabel1.setText("SF");

        jLabel2.setText("NR");

        jLabel3.setText("FD");

        jLabel4.setText("LR");

        jLabel5.setText("ITR");

        initTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Random", "Linear" }));

        jLabel9.setText("Initialization");

        jTextField1.setText("0.3");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("4");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("0.1");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setText("0.3");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setText("100");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(initTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(initTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Advance Parameters"));

        jLabel8.setText("Distance");

        jDistance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Euclidean", "Chi-Square", "Cosine" }));

        jLabel7.setText("Parser");

        fileTypeCombo.setModel(new javax.swing.DefaultComboBoxModel());
        fileTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileTypeComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Save Options"));

        saveData.setText("Save Node & Cluster Data");
        saveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDataActionPerformed(evt);
            }
        });

        jLabel10.setText("Number of Clusters :");

        cCountTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel12.setText("/");

        maxCountLbl.setText("N");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cCountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxCountLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveData)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveData)
                    .addComponent(jLabel10)
                    .addComponent(cCountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(maxCountLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("Avg Varience :");

        calcCoeffBtn.setText("Calc Coeff");
        calcCoeffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcCoeffBtnActionPerformed(evt);
            }
        });

        viewMatrixBtn.setText("View Co-oc Matrix");
        viewMatrixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMatrixBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(InputFileLocationTextBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 353, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(trainButton)
                                .addGap(18, 18, 18)
                                .addComponent(viewMatrixBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(plotMapBtn)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coeffTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calcCoeffBtn)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputFileLocationTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(plotMapBtn)
                    .addComponent(trainButton)
                    .addComponent(viewMatrixBtn))
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coeffTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(calcCoeffBtn))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateClusterDataList(Map<String,String> testResultMap,ArrayList<GCluster> clusterList,ArrayList<String> clusterDataList) {
        int i = 1;

        for (GCluster cluster : clusterList) {
            
            ArrayList<GNode> cNodeList = cluster.getcNodes();
            /*Collections.sort(cNodeList,new Comparator<GNode>(){
                @Override
                public int compare(GNode o1, GNode o2) {
                    return o1.getHitValue()-o2.getHitValue();
                }
            });*/
            String clusterDataStr = cluster.getX()+","
                    + cluster.getY()+ ":";
            
            for (int j = 0; j < cNodeList.size(); j++) {
                GNode node = cNodeList.get(j);
                if (testResultMap.containsKey(Utils.generateIndexString(node.getX(), node.getY()))) {
                    //last item, no comma needed
                    if (j == cluster.getcNodes().size() - 1) {
                        clusterDataStr += testResultMap.get(Utils.generateIndexString(node.getX(), node.getY()));
                    } else {
                        clusterDataStr += testResultMap.get(Utils.generateIndexString(node.getX(), node.getY())) + ",";
                    }
                }

            }
            clusterDataList.add(clusterDataStr);
            i++;
        }
    }

    private void populateNodeDataList(Map<String,String> testResultMap, ArrayList<String> nodeDataList) {
        for (Map.Entry<String, String> entry : testResultMap.entrySet()) {
            nodeDataList.add(entry.getKey() + ":" + entry.getValue());
        }
        
    }

    private void trainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainButtonActionPerformed

        GSOMConstants.SPREAD_FACTOR = Double.parseDouble(jTextField1.getText());
        GSOMConstants.MAX_NEIGHBORHOOD_RADIUS = Double.parseDouble(jTextField2.getText());
        GSOMConstants.START_LEARNING_RATE = Double.parseDouble(jTextField4.getText());
        GSOMConstants.MAX_ITERATIONS = Integer.parseInt(jTextField5.getText());
        
        if (jDistance.getSelectedIndex() == 0) {
            distance = 0;
        } else if(jDistance.getSelectedIndex()==1){
            distance = 1;
        }else{
            distance = 2;
        }
        
        InitType initType=null;
        if(initTypeCombo.getSelectedIndex()==0){
        initType = InitType.RANDOM;
        }else if(initTypeCombo.getSelectedIndex()==1){
            initType = InitType.LINEAR;
        }
        gRun = new GSOMRun(initType,this);

        InputDataType type = InputDataType.NUMERICAL;

        String typeStr = (String) fileTypeCombo.getSelectedItem();
        if (typeStr.equalsIgnoreCase("NUMERICAL")) {
            type = InputDataType.NUMERICAL;
        } else if (typeStr.equalsIgnoreCase("FLAGS")) {
            type = InputDataType.FLAGS;
        } else if (typeStr.equalsIgnoreCase("ASHES")) {
            type = InputDataType.ASHES;
        }

        gRun.runTraining(InputFileLocationTextBox.getText(), type);


    }//GEN-LAST:event_trainButtonActionPerformed

    private void plotMapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotMapBtnActionPerformed
        int cCount = Integer.parseInt(cCountTxt.getText())-2;
        createTheXYPlot(gRun.getGSOMMap(), gRun.getTestResultMap(), gRun.getAllClusters().get(cCount));
    }//GEN-LAST:event_plotMapBtnActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JFileChooser chooser = new JFileChooser(".");//E:\GSOM2_v3\GSOM2

        int choice = chooser.showOpenDialog(null);

        if (choice != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File chosenFile = chooser.getSelectedFile();
        //JOptionPane.showMessageDialog(null,chosenFile.getAbsolutePath());
        InputFileLocationTextBox.setText(chosenFile.getAbsolutePath());

    }//GEN-LAST:event_browseButtonActionPerformed

    private void fileTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileTypeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileTypeComboActionPerformed
    private ImageNetworkController imgNetController;
    private SingleNodeImageController sNodeController;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        imgNetController = new ImageNetworkController(this);
        imgNetController.displayView();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDataActionPerformed
        Map<String, String> testResultMap = gRun.getTestResultMap();
        
        nodeDataList = new ArrayList<String>();
        populateNodeDataList(testResultMap,nodeDataList);
        
        clusterDataList = new ArrayList<String>();
        ArrayList<ArrayList<GCluster>> clusterList = gRun.getAllClusters();
        int cCount = Integer.parseInt(cCountTxt.getText());
        int cListIdx = cCount-2;
        if(cListIdx > clusterList.size()-1){
            JOptionPane.showMessageDialog(null, "Enter a number less than "+(clusterList.size()+2));
        }else{
            populateClusterDataList(testResultMap,clusterList.get(cListIdx),clusterDataList);
            GFileHandler.writeFile("ClusterData.txt", clusterDataList);
            GFileHandler.writeFile("NodeData.txt", nodeDataList);
        }
    }//GEN-LAST:event_saveDataActionPerformed

    private void calcCoeffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcCoeffBtnActionPerformed
        int cCount = Integer.parseInt(cCountTxt.getText());
        coeffTxt.setText(gRun.getSilCoeff(cCount)+"");
    }//GEN-LAST:event_calcCoeffBtnActionPerformed

    private void viewMatrixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMatrixBtnActionPerformed
        JFrame matrixf = new JFrame();
        matrixf.setSize(800,500);
        EucDistOccMat matCal = new EucDistOccMat();
        JTable table = matCal.generateMatrix(gRun.getGSOMMap(),GSOMConstants.DIMENSIONS);
        JScrollPane scroll = new JScrollPane(table);
        scroll.setSize(750,480);
        matrixf.getContentPane().add(scroll);
        
        matrixf.setVisible(true);
    }//GEN-LAST:event_viewMatrixBtnActionPerformed

    @Override
    public void clickedOnImage(String key, ArrayList<String> values) {
        sNodeController = new SingleNodeImageController();
        sNodeController.setDirPath(getFolderPath(gridImageLoc));
        sNodeController.showView(key, values);
    }
    private String gridImageLoc;

    @Override
    public void gridImageLocSet(String path) {
        gridImageLoc = path;
    }

    private String getFolderPath(String path) {
        if (path == null || path.length() <= 0) {
            return "";
        }

        String[] tokens = path.split("\\\\");
        String dirLoc = "";
        for (int i = 0; tokens.length > 0 && i < tokens.length - 1; i++) {
            dirLoc += tokens[i] + "\\\\";
        }
        return dirLoc;
    }
    private GSOMRun gRun;

    private ArrayList<String> nodeDataList;
    private ArrayList<String> clusterDataList;
    
    @Override
    public void executionCompleted() {
        
        cCountTxt.setText((gRun.getBestCount()+ 2)+"");
        maxCountLbl.setText(gRun.getAllClusters().size()+1+"");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainWindow().setVisible(true);

            }
        });
    }


    private void createTheXYPlot(Map<String, GNode> map, final Map<String, String> testResults, ArrayList<GCluster> clusters) {
        ArrayList<Color> plotColors = getColorArray(12);

        XYToolTipGenerator tipGen = new XYToolTipGenerator() {

            @Override
            public String generateToolTip(XYDataset xyd, int i1, int i2) {
                int dX = (int) xyd.getXValue(i1, i2);
                int dY = (int) xyd.getYValue(i1, i2);
                String str = testResults.get(Utils.generateIndexString(dX, dY));
                //if(str==null){
                //String str = "Dummy Node";
                //}
                return str;
            }
        };

        XYLineAndShapeRenderer nonHitRend = new XYLineAndShapeRenderer();
        nonHitRend.setSeriesPaint(0, new Color(0, 0, 0));
        nonHitRend.setBaseLinesVisible(false);

        ArrayList<XYSeries> seriesSet = new ArrayList<XYSeries>();

        /*
         * // identify non-hit nodes first XYSeries nonHitSeries = new
         * XYSeries("Non-hit nodes"); for(GNode node : map.values()){
         * if(!testResults.containsKey(Utils.generateIndexString(node.getX(),
         * node.getY()))){ nonHitSeries.add(node.getX(),node.getY()); } }
         * seriesSet.add(nonHitSeries);
         */

        int idx = 0;
        for (GCluster cluster : clusters) {
            XYSeries temp = new XYSeries("cluster" + idx);
            for (GNode node : cluster.getcNodes()) {
                //if(testResults.containsKey(Utils.generateIndexString(node.getX(), node.getY()))){
                    temp.add(node.getX(), node.getY());
                //}
            }
            seriesSet.add(temp);
            idx++;
        }

        ArrayList<XYDataset> dataset = new ArrayList<XYDataset>();
        for (XYSeries series : seriesSet) {
            dataset.add(new XYSeriesCollection(series));
        }

        //XYDataset nonHitDataset = new XYSeriesCollection(nonHitSeries);

        JFreeChart chart = ChartFactory.createScatterPlot("GSOM Network", "X", "Y", null, PlotOrientation.HORIZONTAL, false, true, false);

        XYPlot plot = (XYPlot) chart.getPlot();




        for (int j = 0; j < dataset.size(); j++) {

            XYLineAndShapeRenderer rend = new XYLineAndShapeRenderer();
            rend.setBaseToolTipGenerator(tipGen);
            rend.setBaseLinesVisible(false);
            //rend.setSeriesPaint(0, plotColors.get(j));            
            //rend.setSeriesPaint(1, plotColors.get(j));            
            rend.setSeriesShape(0, ShapeUtilities.createDiagonalCross(3, .3f));
            plot.setDataset(j, dataset.get(j));
            plot.setRenderer(j, rend);


        }


//        ChartPanel chartpanel = new ChartPanel(chart, false, false, false, false, false);
//        chartpanel.addMouseListener(chartpanel);
        //plot.setDataset(1,nonHitDataset);
        //plot.setRenderer(1,nonHitRend);

        ChartFrame cFrame = new ChartFrame("GSOM Network", chart);
        cFrame.setSize(450, 500);
        cFrame.setVisible(true);

        try {
            saveToFile(chart, "test.jpg", 450, 500, 100);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void createTheXYPlotHitAndNonHit(Map<String, GNode> map, final Map<String, String> testResults) {

        XYToolTipGenerator tipGen = new XYToolTipGenerator() {

            @Override
            public String generateToolTip(XYDataset xyd, int i1, int i2) {
                int dX = (int) xyd.getXValue(i1, i2);
                int dY = (int) xyd.getYValue(i1, i2);
                String str = testResults.get(Utils.generateIndexString(dX, dY));

                return str;
            }
        };

        XYLineAndShapeRenderer rend = new XYLineAndShapeRenderer();
        rend.setSeriesPaint(0, Color.black);
        rend.setSeriesPaint(1, Color.red);
        rend.setBaseLinesVisible(false);

        XYSeries hitSeries = new XYSeries("Hit nodes");
        XYSeries nonHitSeries = new XYSeries("Non-hit nodes");

        // identify non-hit nodes first
        for (GNode node : map.values()) {
            if (!testResults.containsKey(Utils.generateIndexString(node.getX(), node.getY()))) {
                nonHitSeries.add(node.getX(), node.getY());
            } else {
                hitSeries.add(node.getX(), node.getY());
            }
        }

        XYDataset hDataset = new XYSeriesCollection(hitSeries);
        XYDataset nhDataset = new XYSeriesCollection(nonHitSeries);

        JFreeChart chart = ChartFactory.createScatterPlot("GSOM Network", "X", "Y", null, PlotOrientation.HORIZONTAL, false, true, false);

        XYPlot plot = (XYPlot) chart.getPlot();

        rend.setSeriesShape(0, ShapeUtilities.createDiagonalCross(3, .3f));
        plot.setDataset(0, hDataset);
        plot.setDataset(1, nhDataset);
        plot.setRenderer(0, rend);
        plot.setRenderer(1, rend);

        ChartFrame cFrame = new ChartFrame("GSOM Network", chart);
        cFrame.setSize(450, 500);
        cFrame.setVisible(true);


        try {
            saveToFile(chart, "e:/test1.jpg", 450, 500, 100);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputFileLocationTextBox;
    private javax.swing.JButton browseButton;
    private javax.swing.JTextField cCountTxt;
    private javax.swing.JButton calcCoeffBtn;
    private javax.swing.JTextField coeffTxt;
    private javax.swing.JComboBox fileTypeCombo;
    private javax.swing.JComboBox initTypeCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jDistance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel maxCountLbl;
    private javax.swing.JButton plotMapBtn;
    private javax.swing.JButton saveData;
    private javax.swing.JTextArea statusTextArea;
    private javax.swing.JButton trainButton;
    private javax.swing.JButton viewMatrixBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void stepCompleted(String str) {
        statusTextArea.append(str + "\n");
    }
}
